# Generated by Django 4.2.10 on 2024-03-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Email_address', models.EmailField(max_length=100, unique=True)),
                ('Phone_number', models.IntegerField(unique=True)),
                ('Date_and_time', models.DateTimeField()),
                ('Meeting_point', models.CharField(max_length=200)),
                ('Special_requirements', models.CharField(max_length=200)),
            ],
        ),
    ]
